# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: publish

on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  test:
    uses: astrawan/expo-nkeys/.github/workflows/reusable-test.yml@main
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    environment: 'npm'
    needs: [test]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - name: publish
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
