# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  test:
    uses: astrawan/expo-nkeys/.github/workflows/reusable-test.yml@main
    secrets: inherit
